In [1]:
lst=[10,20,30,40,50,60,70,80,90]
print("Content of list =",lst)


Content of list = [10, 20, 30, 40, 50, 60, 70, 80, 90]


In [14]:
import numpy as np
lst=[10,20,30,40,50,60,70,80,90]
a = np.array(lst)
print("Dimention of ndarray =",a.ndim)
print("Content of ndarray =",a)

Dimention of ndarray = 1
Content of ndarray = [10 20 30 40 50 60 70 80 90]


In [10]:
import numpy as np
lst=[10,20,30,40,50,60,70,80,90]
a = np.array(lst)
print("Content of ndarray =",a)
a.shape=(3,3) #reshape the ndarray into 3*3 matrix
print("Dimention of ndarray =",a.ndim)
print(a)

Content of ndarray = [10 20 30 40 50 60 70 80 90]
Dimention of ndarray = 2
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
import numpy as np
lst=[10,20,30,40,50,60,70,80,90,10,20,30]
a = np.array(lst)
print("Content of ndarray =",a)
a.shape=(2,2,3)
print("Dimention of ndarray =",a.ndim)
print(a)

Content of ndarray = [10 20 30 40 50 60 70 80 90 10 20 30]
Dimention of ndarray = 3
[[[10 20 30]
  [40 50 60]]

 [[70 80 90]
  [10 20 30]]]


In [11]:
import numpy as np
lst=[10,20,30,40,50,60,70,80,90,10,20,30,1,2,3,4]
a = np.array(lst)
print("Content of ndarray =",a)
a.shape=(2,2,2,2)
print("Dimention of ndarray =",a.ndim)
print(a)

Content of ndarray = [10 20 30 40 50 60 70 80 90 10 20 30  1  2  3  4]
Dimention of ndarray = 4
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90 10]
   [20 30]]

  [[ 1  2]
   [ 3  4]]]]
