In [4]:
#Creating an Object of ndarray by using  array()
#int
import numpy as np
a=10
a1=np.array(a)
print("Content of ndarray = {} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 0
print("Shape of ndarray = {}".format(a1.shape)) # ()
print("Size of ndarray = {}".format(a1.size)) # 1

Content of ndarray = 10 type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 0
Shape of ndarray = ()
Size of ndarray = 1


In [5]:
#Creating an Object of ndarray by using  array()
#float
import numpy as np
a=10.10
a1=np.array(a)
print("Content of ndarray = {} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 0
print("Shape of ndarray = {}".format(a1.shape)) # ()
print("Size of ndarray = {}".format(a1.size)) # 1

Content of ndarray = 10.1 type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 0
Shape of ndarray = ()
Size of ndarray = 1


In [6]:
#Creating an Object of ndarray by using  array()
#complex
import numpy as np
a=10+3j
a1=np.array(a)
print("Content of ndarray = {} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 0
print("Shape of ndarray = {}".format(a1.shape)) # ()
print("Size of ndarray = {}".format(a1.size)) # 1

Content of ndarray = (10+3j) type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 0
Shape of ndarray = ()
Size of ndarray = 1


In [7]:
#Creating an Object of ndarray by using  array()
#str
import numpy as np
a="Python"
a1=np.array(a)
print("Content of ndarray = {} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 0
print("Shape of ndarray = {}".format(a1.shape)) # ()
print("Size of ndarray = {}".format(a1.size)) # 1

Content of ndarray = Python type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 0
Shape of ndarray = ()
Size of ndarray = 1


In [8]:
#Creating an Object of ndarray by using  array()
#range
import numpy as np
a=range(10)
a1=np.array(a)
print("Content of ndarray = {} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 1
print("Shape of ndarray = {}".format(a1.shape)) # (10,)
print("Size of ndarray = {}".format(a1.size)) # 10

Content of ndarray = [0 1 2 3 4 5 6 7 8 9] type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 1
Shape of ndarray = (10,)
Size of ndarray = 10


In [10]:
#Creating an Object of ndarray by using  array()
#range
import numpy as np
a=range(10,21,2)
a1=np.array(a)
print("Content of ndarray = {} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 1
print("Shape of ndarray = {}".format(a1.shape)) # (6,)
print("Size of ndarray = {}".format(a1.size)) # 6

Content of ndarray = [10 12 14 16 18 20] type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 1
Shape of ndarray = (6,)
Size of ndarray = 6


In [12]:
#Creating an Object of ndarray by using  array()
#range
import numpy as np
a=range(10)
a1=np.array(a).reshape(5,2)
print("Content of ndarray\n{} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 2
print("Shape of ndarray = {}".format(a1.shape)) # (5,2)
print("Size of ndarray = {}".format(a1.size)) # 10

Content of ndarray
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 2
Shape of ndarray = (5, 2)
Size of ndarray = 10


In [14]:
#Creating an Object of ndarray by using  array()
#range
import numpy as np
a=range(0,16)
a1=np.array(a)
a1.shape = (4,4)
print("Content of ndarray\n{} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 2
print("Shape of ndarray = {}".format(a1.shape)) # (4,4)
print("Size of ndarray = {}".format(a1.size)) # 16

Content of ndarray
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 2
Shape of ndarray = (4, 4)
Size of ndarray = 16


In [15]:
#Creating an Object of ndarray by using  array()
#range
import numpy as np
a=range(0,16)
a1=np.array(a)
a1.shape = (2,2,4)
print("Content of ndarray\n{} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 3
print("Shape of ndarray = {}".format(a1.shape)) # (2,2,4)
print("Size of ndarray = {}".format(a1.size)) # 16

Content of ndarray
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 3
Shape of ndarray = (2, 2, 4)
Size of ndarray = 16


In [17]:
#Creating an Object of ndarray by using  array()
#range
import numpy as np
a=range(0,16)
a1=np.array(a)
a1.shape = (2,2,2,2)
print("Content of ndarray\n{} type of ndarray = {}".format(a1,type(a1)))
print("Dimension of ndarray = {}".format(a1.ndim)) # 4
print("Shape of ndarray = {}".format(a1.shape)) # (2,2,2,2)
print("Size of ndarray = {}".format(a1.size)) # 16

Content of ndarray
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] type of ndarray = <class 'numpy.ndarray'>
Dimension of ndarray = 4
Shape of ndarray = (2, 2, 2, 2)
Size of ndarray = 16


In [18]:
#Creating an Object of ndarray by using  array()
#list
import numpy as np
lst=[[10,20],[30,40],[50,60],[70,80]]
a=np.array(lst,float)
print("Content of ndarray\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  #  2
print("Shape of ndarray={}".format(a.shape))   #  (4,2)
print("Size of ndarray={}".format(a.size)) # 8
print("Data type Elements of ndarray={}".format(a.dtype)) # float64

Content of ndarray
[[10. 20.]
 [30. 40.]
 [50. 60.]
 [70. 80.]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(4, 2)
Size of ndarray=8
Data type Elements of ndarray=float64


In [20]:
#Creating an Object of ndarray by using  array()
#list
import numpy as np
lst=[10,20,30,40,50,60,70,80,90,15,25,35]
a=np.array(lst,float).reshape(4,3)
print("Content of ndarray\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  #  2
print("Shape of ndarray={}".format(a.shape))   #  (4,3)
print("Size of ndarray={}".format(a.size)) # 12
print("Data type Elements of ndarray={}".format(a.dtype)) # float64

Content of ndarray
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]
 [15. 25. 35.]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(4, 3)
Size of ndarray=12
Data type Elements of ndarray=float64


In [23]:
#Creating an Object of ndarray by using  array()
#list
import numpy as np
lst=[10,20,30,40,50,60,70,80,90,15,25,35,45,55,65,75]
a=np.array(lst,float).reshape(2,2,2,2)
print("Content of ndarray\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  #  4
print("Shape of ndarray={}".format(a.shape))   #  (2,2,2,2)
print("Size of ndarray={}".format(a.size)) # 16
print("Data type Elements of ndarray={}".format(a.dtype)) # float64

Content of ndarray
[[[[10. 20.]
   [30. 40.]]

  [[50. 60.]
   [70. 80.]]]


 [[[90. 15.]
   [25. 35.]]

  [[45. 55.]
   [65. 75.]]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =4
Shape of ndarray=(2, 2, 2, 2)
Size of ndarray=16
Data type Elements of ndarray=float64


In [24]:
a

array([[[[10., 20.],
         [30., 40.]],

        [[50., 60.],
         [70., 80.]]],


       [[[90., 15.],
         [25., 35.]],

        [[45., 55.],
         [65., 75.]]]])

In [26]:
a=a.astype(int)
print(a)

[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90 15]
   [25 35]]

  [[45 55]
   [65 75]]]]


In [27]:
a

array([[[[10, 20],
         [30, 40]],

        [[50, 60],
         [70, 80]]],


       [[[90, 15],
         [25, 35]],

        [[45, 55],
         [65, 75]]]])

In [28]:
#Creating an Object of ndarray by using  array()
#set
import numpy as np
s1={10,20,30,40,50,60,70,80,90}
a=np.array(s1)
print("Content of ndarray={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  # 0
print("Shape of ndarray={}".format(a.shape))   # () 
print("Size of ndarray={}".format(a.size)) # 1 
print("Data type Elements of ndarray={}".format(a.dtype)) #Object

Content of ndarray={70, 40, 10, 80, 50, 20, 90, 60, 30}  Type=<class 'numpy.ndarray'>
Dimension ndarray =0
Shape of ndarray=()
Size of ndarray=1
Data type Elements of ndarray=object


In [29]:
#Creating an Object of ndarray by using  array()
#dict
import numpy as np
s1={1:"PYTHON",2:"C",3:"C++",4:"Java"}
print("Content of s1={}  Type s1={}".format(s1,type(s1)))
a=np.array(s1)
print("Content of ndarray={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  # 0 
print("Shape of ndarray={}".format(a.shape))   # () 
print("Size of ndarray={}".format(a.size)) # 1 
print("Data type Elements of ndarray={}".format(a.dtype)) #object

Content of s1={1: 'PYTHON', 2: 'C', 3: 'C++', 4: 'Java'}  Type s1=<class 'dict'>
Content of ndarray={1: 'PYTHON', 2: 'C', 3: 'C++', 4: 'Java'}  Type=<class 'numpy.ndarray'>
Dimension ndarray =0
Shape of ndarray=()
Size of ndarray=1
Data type Elements of ndarray=object


In [30]:
#Creating an Object of ndarray by using  array()
#None
import numpy as np
s1=None
print("Content of s1={}  Type s1={}".format(s1,type(s1)))
a=np.array(s1)
print("Content of ndarray={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  # 0 
print("Shape of ndarray={}".format(a.shape))   # () 
print("Size of ndarray={}".format(a.size)) # 1 
print("Data type Elements of ndarray={}".format(a.dtype)) #object

Content of s1=None  Type s1=<class 'NoneType'>
Content of ndarray=None  Type=<class 'numpy.ndarray'>
Dimension ndarray =0
Shape of ndarray=()
Size of ndarray=1
Data type Elements of ndarray=object


In [32]:
#Creating an Object of ndarray by using  array()
#tuple
import numpy as np
t=(10,20,30,40,50,60)
print("Content of t={}  Type t={}".format(t,type(t)))
a=np.array(t).reshape(3,2)
print("Content of ndarray={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  # 2 
print("Shape of ndarray={}".format(a.shape))   # (3,2) 
print("Size of ndarray={}".format(a.size)) # 6 
print("Data type Elements of ndarray={}".format(a.dtype)) #int64

Content of t=(10, 20, 30, 40, 50, 60)  Type t=<class 'tuple'>
Content of ndarray=[[10 20]
 [30 40]
 [50 60]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(3, 2)
Size of ndarray=6
Data type Elements of ndarray=int64
