In [8]:
#varname=numpy.arange(Value)
import numpy as np
a=np.arange(16).reshape(2,2,2,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  #  4 
print("Shape of ndarray={}".format(a.shape))   #  (2,2,2,2)
print("Size of ndarray={}".format(a.size)) #  16

content of a
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =4
Shape of ndarray=(2, 2, 2, 2)
Size of ndarray=16


In [7]:
#varname=numpy.arange(start,stop)
import numpy as np
a=np.arange(0,16).reshape(2,2,2,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  #  4 
print("Shape of ndarray={}".format(a.shape))   #  (2,2,2,2)
print("Size of ndarray={}".format(a.size)) #  16

content of a
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =4
Shape of ndarray=(2, 2, 2, 2)
Size of ndarray=16


In [6]:
#varname=numpy.arange(start,stop,step)
import numpy as np
a=np.arange(0,32,2).reshape(2,2,2,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  #  4 
print("Shape of ndarray={}".format(a.shape))   #  (2,2,2,2)
print("Size of ndarray={}".format(a.size)) #  16

content of a
[[[[ 0  2]
   [ 4  6]]

  [[ 8 10]
   [12 14]]]


 [[[16 18]
   [20 22]]

  [[24 26]
   [28 30]]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =4
Shape of ndarray=(2, 2, 2, 2)
Size of ndarray=16


In [ ]:
#varname=numpy.arange(start,stop)
import numpy as np
a=np.arange(0,21).reshape(2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  #  4 
print("Shape of ndarray={}".format(a.shape))   #  (2,2,2,2)
print("Size of ndarray={}".format(a.size)) #  16