In [6]:
#Code for Building  a Matrix with dim of 2 with All entries as 0
import numpy as np
lst=[0,0,0,0]
a=np.array(lst).reshape(2,2)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[0 0]
 [0 0]]
Dimension of a = 2


In [7]:
#Create an object of ndarray with 6 Zeros 
a=np.zeros(6)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[0. 0. 0. 0. 0. 0.]
Dimension of a = 1


In [8]:
#Create an object of ndarray with 6 Zeros 
a=np.zeros(6,int)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[0 0 0 0 0 0]
Dimension of a = 1


In [11]:
#Create an object of ndarray with 9 Zeros with 2-D
a=np.zeros((3,3),dtype=int)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Dimension of a = 2


In [12]:
#Create an object of ndarray with 16 Zeros with 4-D
a=np.zeros((2,2,2,2),dtype=int)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]
Dimension of a = 4


In [13]:
#Create an object of ndarray with 6 Ones
a=np.ones(6,int)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[1 1 1 1 1 1]
Dimension of a = 1


In [14]:
#Create an object of ndarray with 16 Ones
a=np.ones((2,2,2,2),int)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]
Dimension of a = 4


In [15]:
#Create an object of ndarray with 6 Entries as 3
a=np.full(6,3)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[3 3 3 3 3 3]
Dimension of a = 1


In [16]:
#Create an object of ndarray with 12 Entries as 4
a=np.full((3,4),4)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
Dimension of a = 2


In [18]:
#Create an object of ndarray with 12 Entries as 4
a=np.full(fill_value=4,shape=(3,4))
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
Dimension of a = 2


In [19]:
#Syntax:  varname=numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype)

In [20]:
#Syntax:  varname=numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype)
a=np.linspace(0,10,num=20)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
Dimension of a = 1


In [23]:
#Syntax:  varname=numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype)
a=np.linspace(0,10,num=10,endpoint=False)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Dimension of a = 1


In [25]:
#Syntax:  varname=numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype)
a=np.linspace(0,10,num=10,endpoint=False,retstep=True)
print("Content of a\n{}".format(a[0]))
print("-------------------------------------------------------------------------")
print("Return Step of a =",a[1])

Content of a
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
-------------------------------------------------------------------------
Return Step of a = 1.0


In [26]:
#Syntax:  varname=numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype)
a=np.linspace(0,10,num=40,endpoint=False,retstep=True)
print("Content of a\n{}".format(a[0]))
print("-------------------------------------------------------------------------")
print("Return Step of a =",a[1])

Content of a
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75
 7.   7.25 7.5  7.75 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]
-------------------------------------------------------------------------
Return Step of a = 0.25


In [27]:
#=>Syntax:  varname=numpy.identity(N,dtype)

In [28]:
#=>Syntax:  varname=numpy.identity(N,dtype)
a=np.identity(3)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Dimension of a = 2


In [29]:
#=>Syntax:  varname=numpy.identity(N,dtype)
a=np.identity(3,int)
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))

Content of a
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Dimension of a = 2


In [ ]:
#=>Syntax:  varname=numpy.identity(N,dtype)
a=np.identity()
print("Content of a\n{}".format(a))
print("Dimension of a = {}".format(a.ndim))