In [1]:
#Syntax:	varname=numpy.eye(N,M=None,k=0,dtype)
#Generates Unit OR Identity Matrix within Square OR Rectagle Matrix

In [2]:
import numpy as np
a=np.eye(3)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
Dim of a= 2


In [3]:
import numpy as np
a=np.eye(3,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]] <class 'numpy.ndarray'>
Dim of a= 2


In [4]:
import numpy as np
a=np.eye(3,k=1,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 1 0]
 [0 0 1]
 [0 0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [5]:
import numpy as np
a=np.eye(3,k=-2,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 0 0]
 [0 0 0]
 [1 0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [6]:
import numpy as np
a=np.eye(3,k=-3,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 0 0]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [7]:
import numpy as np
a=np.eye(7,k=-4,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]] <class 'numpy.ndarray'>
Dim of a= 2
