In [1]:
#varname=numpy.hstack( (ndarrayobj1,ndarrayobj2) )

In [6]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
b=np.array([[15,25],[35,45],[55,65]])
print("Matrix-B")
print(b)
print("Dimension of b=",b.ndim)
print("Shape of B=",b.shape)
print("-----------------------------------------")

c=np.hstack((a,b))
print("Matrix-C")
print(c)
print("Dimension of c=",c.ndim)
print("Shape of C=",c.shape)
print("-----------------------------------------")


Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a= 2
Shape of A= (3, 3)
-----------------------------------------
Matrix-B
[[15 25]
 [35 45]
 [55 65]]
Dimension of b= 2
Shape of B= (3, 2)
-----------------------------------------
Matrix-C
[[10 20 30 15 25]
 [40 50 60 35 45]
 [70 80 90 55 65]]
Dimension of c= 2
Shape of C= (3, 5)
-----------------------------------------


In [7]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
b=np.array([[15,25],[35,45],[55,65]])
print("Matrix-B")
print(b)
print("Dimension of b=",b.ndim)
print("Shape of B=",b.shape)
print("-----------------------------------------")
c=np.hstack((b,a))
print("Matrix-C")
print(c)
print("Dimension of c=",c.ndim)
print("Shape of C=",c.shape)
print("-----------------------------------------")

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a= 2
Shape of A= (3, 3)
-----------------------------------------
Matrix-B
[[15 25]
 [35 45]
 [55 65]]
Dimension of b= 2
Shape of B= (3, 2)
-----------------------------------------
Matrix-C
[[15 25 10 20 30]
 [35 45 40 50 60]
 [55 65 70 80 90]]
Dimension of c= 2
Shape of C= (3, 5)
-----------------------------------------


In [8]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
b=np.array([[15,25,55],[35,45,65]])
print("Matrix-B")
print(b)
print("Dimension of b=",b.ndim)
print("Shape of B=",b.shape)
print("-----------------------------------------")

c=np.vstack((a,b))
print("Matrix-C")
print(c)
print("Dimension of c=",c.ndim)
print("Shape of C=",c.shape)
print("-----------------------------------------")

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a= 2
Shape of A= (3, 3)
-----------------------------------------
Matrix-B
[[15 25 55]
 [35 45 65]]
Dimension of b= 2
Shape of B= (2, 3)
-----------------------------------------
Matrix-C
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 25 55]
 [35 45 65]]
Dimension of c= 2
Shape of C= (5, 3)
-----------------------------------------


In [9]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
b=np.array([[15,25,55],[35,45,65]])
print("Matrix-B")
print(b)
print("Dimension of b=",b.ndim)
print("Shape of B=",b.shape)
print("-----------------------------------------")

c=np.vstack((b,a))
print("Matrix-C")
print(c)
print("Dimension of c=",c.ndim)
print("Shape of C=",c.shape)
print("-----------------------------------------")

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a= 2
Shape of A= (3, 3)
-----------------------------------------
Matrix-B
[[15 25 55]
 [35 45 65]]
Dimension of b= 2
Shape of B= (2, 3)
-----------------------------------------
Matrix-C
[[15 25 55]
 [35 45 65]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of c= 2
Shape of C= (5, 3)
-----------------------------------------


In [10]:
#Syntax:  varname=numpy.diag(ndarray,k)

In [12]:
import numpy as np
a=np.arange(9).reshape(3,3)
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
pd=np.diag(a)
print("Principle Diagonal=",pd)

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Dimension of a= 2
Shape of A= (3, 3)
-----------------------------------------
Principle Diagonal= [0 4 8]


In [13]:
import numpy as np
a=np.arange(9).reshape(3,3)
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
pd=np.diag(a,2)
print("Principle Diagonal=",pd)

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Dimension of a= 2
Shape of A= (3, 3)
-----------------------------------------
Principle Diagonal= [2]


In [14]:
import numpy as np
a=np.arange(16).reshape(4,4)
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
pd=np.diag(a)
print("Principle Diagonal=",pd)

Matrix-A
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Dimension of a= 2
Shape of A= (4, 4)
-----------------------------------------
Principle Diagonal= [ 0  5 10 15]


In [15]:
import numpy as np
a=np.arange(16).reshape(4,4)
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
pd=np.diag(a,k=3)
print("Principle Diagonal=",pd)

Matrix-A
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Dimension of a= 2
Shape of A= (4, 4)
-----------------------------------------
Principle Diagonal= [3]


In [16]:
import numpy as np
a=np.arange(16).reshape(4,4)
print("Matrix-A")
print(a)
print("Dimension of a=",a.ndim)
print("Shape of A=",a.shape)
print("-----------------------------------------")
pd=np.diag(a,k=-2)
print("Principle Diagonal=",pd)

Matrix-A
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Dimension of a= 2
Shape of A= (4, 4)
-----------------------------------------
Principle Diagonal= [ 8 13]
