In [1]:
#Syntax-1: varname=numpy.random.randint(Value)-----------------> Random Number from 0 to Value-1

In [2]:
import numpy.random as r
val = r.randint(5)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 4  Type = <class 'int'>


In [3]:
for i in range(1,6):
    val = r.randint(5)
    print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 2  Type = <class 'int'>
Random Value = 2  Type = <class 'int'>
Random Value = 2  Type = <class 'int'>
Random Value = 2  Type = <class 'int'>
Random Value = 0  Type = <class 'int'>


In [4]:
#Syntax-2:varname=numpy.random.randint(Low,High)-----> Random Number from Low to High-1

In [5]:
val = r.randint(1,50)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 34  Type = <class 'int'>


In [6]:
for i in range(1,6):
    val = r.randint(1,50)
    print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 44  Type = <class 'int'>
Random Value = 35  Type = <class 'int'>
Random Value = 21  Type = <class 'int'>
Random Value = 31  Type = <class 'int'>
Random Value = 34  Type = <class 'int'>


In [7]:
#Syntax-3:varname=numpy.random.randint(Low,High,size)

In [8]:
val = r.randint(1,50,5)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [41 49 13 41 31]  Type = <class 'numpy.ndarray'>


In [9]:
val = r.randint(1,50,(5,5))
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [[11 43  5  9  9]
 [33  2 29 29 32]
 [34 34 34  2  9]
 [13 43 17 41 44]
 [44  5 19 11 21]]  Type = <class 'numpy.ndarray'>


In [10]:
val = r.randint(1,50,(2,5,5))
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [[[31 18  1 27 13]
  [19 14 41 11 46]
  [12 35 25 34 42]
  [27 10  1 14 13]
  [34  1 27 45 44]]

 [[ 7 22 37 33 33]
  [43 43  5 12 17]
  [27  1 36  9  7]
  [21  5 25 44 46]
  [22  3 46 28 32]]]  Type = <class 'numpy.ndarray'>
