In [1]:
#Syntax:varname=numpy.random.randn()----->Gives Random Floating Point Value 

In [2]:
import numpy.random as r
val=r.randn()
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = -1.159635806651895  Type = <class 'float'>


In [3]:
val=r.randn()
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = 0.8839717621945067  Type = <class 'float'>


In [5]:
for i in range(1,6):
    val=r.randn()
    print("Random floating value = {}  Type = {}".format(val,type(val)))
    

Random floating value = -1.877151041398919  Type = <class 'float'>
Random floating value = 0.4287339615031952  Type = <class 'float'>
Random floating value = -0.9714258797127912  Type = <class 'float'>
Random floating value = -0.4674042157416172  Type = <class 'float'>
Random floating value = 0.4227792954445009  Type = <class 'float'>


In [6]:
#Syntax:varname=numpy.random.randn(Value)
#Gives  Number of Random Floating Point Values Depends on 'Value'-- +VE OR -VE---1D

In [7]:
val=r.randn(6)
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = [-0.15101398 -0.42088559 -0.35961806  0.47245676  0.78223353 -0.8951324 ]  Type = <class 'numpy.ndarray'>


In [8]:
#Syntax: varname=numpy.random.randn(Rows,Cols)
#Gives  Number of Random Floating Point Values Depends on 'Rows x Cols'-- +VE OR -VE---2D

In [9]:
val=r.randn(6,6)
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = [[ 0.5935741   0.63860304  0.95841529  0.72643494  0.15346168  0.80519446]
 [ 0.91038149 -1.4501468   1.38736676  1.44166907  0.04241574  1.18442559]
 [ 1.05977547 -1.83547362  0.35395204  0.65258196 -0.32425318 -0.56670499]
 [-0.13175346 -1.04390594 -1.71311562  1.32057298 -1.18827971  0.16114395]
 [ 0.29167207 -1.06392139  0.55223043  1.25725604  0.6810928   0.41510498]
 [-0.22069945  0.04169381 -1.02120799  0.67098781  0.0935569   0.67744183]]  Type = <class 'numpy.ndarray'>


In [10]:
val=r.randn(2,3,3)
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = [[[-3.62748388e-01 -5.31615464e-01 -6.81298977e-01]
  [ 1.64199143e+00 -3.17763979e-01 -1.33867972e-01]
  [-1.23020106e-03 -1.51268341e+00  3.46900515e-01]]

 [[ 1.47034426e-01 -1.38950313e+00  3.47694554e-01]
  [-1.99106599e+00  9.30676881e-01 -1.08335658e+00]
  [-7.03167371e-01 -3.93336065e-01  2.04663193e-01]]]  Type = <class 'numpy.ndarray'>


In [11]:
val=r.randn(2,3,3)
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = [[[-0.04236694 -0.12670206 -0.16565518]
  [-0.14299329 -1.26242531  0.5137667 ]
  [-0.61491314  0.60966802 -0.68720144]]

 [[ 1.09974936 -0.0575056   0.44694665]
  [ 1.18698508  1.67916388  0.19802274]
  [-3.0005712  -0.41724164 -0.64056924]]]  Type = <class 'numpy.ndarray'>


In [12]:
#Syntax:    varname=numpy.random.normal(loc=0,scale=1,size=None)

In [13]:
val=r.normal()
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = -0.37777453005224776  Type = <class 'float'>


In [15]:
for i in range(1,6):
    val=r.normal()
    print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = 0.41501162051922774  Type = <class 'float'>
Random floating value = 1.9587433198632114  Type = <class 'float'>
Random floating value = 1.7825985069643895  Type = <class 'float'>
Random floating value = -0.42774088551281986  Type = <class 'float'>
Random floating value = 0.9241023498414032  Type = <class 'float'>


In [16]:
val=r.normal(5)
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = 4.8207728592328225  Type = <class 'float'>


In [17]:
val=r.normal(2)
print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = 4.280150081593031  Type = <class 'float'>


In [18]:
for i in range(1,6):
    val=r.normal(10)
    print("Random floating value = {}  Type = {}".format(val,type(val)))

Random floating value = 9.959690622391715  Type = <class 'float'>
Random floating value = 8.662287722144242  Type = <class 'float'>
Random floating value = 9.86466525858563  Type = <class 'float'>
Random floating value = 9.78459546298173  Type = <class 'float'>
Random floating value = 10.15114150531373  Type = <class 'float'>


In [21]:
for i in range(1,6):
    x=r.normal(10,8.5)
    print("Vals={}  Type={}".format(x,type(x)))

Vals=22.514337229387706  Type=<class 'float'>
Vals=3.1965191445425614  Type=<class 'float'>
Vals=2.3275685431497113  Type=<class 'float'>
Vals=11.095183033742867  Type=<class 'float'>
Vals=13.871631703676917  Type=<class 'float'>


In [25]:
for i in range(1,6):
    x=r.normal(10,8.5,(2,2))
    print("---------------------------------------------------")
    print("Vals{}  Type={}".format(x,type(x)))
print("---------------------------------------------------")


---------------------------------------------------
Vals=[[ 0.10108765 18.73760058]
 [19.85999479 27.70817092]]  Type=<class 'numpy.ndarray'>
---------------------------------------------------
Vals=[[ 5.8591025  30.15370592]
 [ 3.79921282  4.97538165]]  Type=<class 'numpy.ndarray'>
---------------------------------------------------
Vals=[[-3.84197482  3.95590689]
 [12.99384507 17.88018879]]  Type=<class 'numpy.ndarray'>
---------------------------------------------------
Vals=[[ 1.03870735 -2.59311914]
 [-1.8238394  20.24285336]]  Type=<class 'numpy.ndarray'>
---------------------------------------------------
Vals=[[23.58376709 17.34026527]
 [32.70038584 10.63886731]]  Type=<class 'numpy.ndarray'>
---------------------------------------------------
