In [1]:
# rand()-----> This Function Generates random sample(s) between 0.0 to 1.0---> Maths [0.0 , 1.0)
#arname=numpy.random.rand()
#varname=numpy.random.rand(Value)
#varname=numpy.random.rand(Rows, Cols)
#varname=numpy.random.rand(No. of Matrices,Rows, Cols)

In [2]:
from numpy import random as r
val=r.rand()
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 0.30521922850512595  Type = <class 'float'>


In [3]:
val=r.rand()
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 0.8485217270566344  Type = <class 'float'>


In [4]:
val=r.rand(6)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [0.14066752 0.42529621 0.94468355 0.80567895 0.50200548 0.7315905 ]  Type = <class 'numpy.ndarray'>


In [5]:
val=r.rand(3,3)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [[0.31275559 0.27828058 0.33717809]
 [0.08960928 0.16067213 0.46929859]
 [0.3777149  0.40560553 0.84308978]]  Type = <class 'numpy.ndarray'>


In [6]:
val=r.rand(2,2,2)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [[[0.86782848 0.63719768]
  [0.08264918 0.49061025]]

 [[0.92742468 0.34561984]
  [0.20879498 0.42709161]]]  Type = <class 'numpy.ndarray'>


In [7]:
val=r.rand(2,2,2,2)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [[[[0.66450349 0.14591359]
   [0.71491141 0.25530039]]

  [[0.90372378 0.14719673]
   [0.6690495  0.29891253]]]


 [[[0.38458845 0.54013562]
   [0.02406532 0.98005117]]

  [[0.15571307 0.02801097]
   [0.47353254 0.26229828]]]]  Type = <class 'numpy.ndarray'>


In [9]:
val.shape=(16,)
print(val)

[0.66450349 0.14591359 0.71491141 0.25530039 0.90372378 0.14719673
 0.6690495  0.29891253 0.38458845 0.54013562 0.02406532 0.98005117
 0.15571307 0.02801097 0.47353254 0.26229828]


In [10]:
for i in val:
    print(i)

0.6645034852875842
0.14591358898100937
0.7149114142024152
0.25530039267860405
0.9037237823965896
0.14719673425623536
0.6690495011970721
0.29891253320292555
0.38458845123773433
0.5401356185500437
0.024065315365888962
0.9800511738431605
0.1557130650162013
0.028010973550125384
0.47353254087764796
0.2622982750136077


In [13]:
for i in val:
    print("%0.2f" %i)

0.66
0.15
0.71
0.26
0.90
0.15
0.67
0.30
0.38
0.54
0.02
0.98
0.16
0.03
0.47
0.26


In [15]:
for i in val:
    print("val=",round(i,2))

val= 0.66
val= 0.15
val= 0.71
val= 0.26
val= 0.9
val= 0.15
val= 0.67
val= 0.3
val= 0.38
val= 0.54
val= 0.02
val= 0.98
val= 0.16
val= 0.03
val= 0.47
val= 0.26


In [16]:
#5. uniform()  :  Uniform Distribution
#------------------------------------------------------------------------
#This Function Generates random sample(s) between Two Intervals(Low,High) According Programmer Choice.
#The Default random sample is low is 0.0 and high is 1.0
#Syntax-1:      varname=numpy.random.uniform()
#Syntax-2:	   varname=numpy.random.uniform(Low,High)	
#Syntax-3:	   varname=numpy.random.uniform(Low,High,size)

In [17]:
from numpy import random as r
val=r.uniform()
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 0.7435728460941948  Type = <class 'float'>


In [18]:
val=r.uniform()
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 0.4400872784828912  Type = <class 'float'>


In [19]:
val=r.uniform(3)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 1.5370060485851054  Type = <class 'float'>


In [20]:
val=r.uniform(3,5)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 4.791021871122204  Type = <class 'float'>


In [21]:
val=r.uniform(10,22)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = 14.553918873132808  Type = <class 'float'>


In [22]:
val=r.uniform(10,22,5)
print("Random Value = {}  Type = {}".format(val,type(val)))

Random Value = [14.56426274 19.08731439 13.48645523 16.79857165 12.44231225]  Type = <class 'numpy.ndarray'>


In [ ]:
val=r.uniform(19.)
print("Random Value = {}  Type = {}".format(val,type(val)))