In [1]:
#1. By using Looping Statements

In [5]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print('---------------------------------------------------')
print("1-DArray Data={}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for val in a:
    print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data=[10 20 30 40 50 60 70 80 90]  Dim=1
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
------------------------------------------


In [19]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print('---------------------------------------------------')
print("1-DArray Data\n{}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for rowElement in a:
    for val in rowElement:
        print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data
[[10 20 30]
 [40 50 60]
 [70 80 90]]  Dim=2
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
------------------------------------------


In [18]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print('---------------------------------------------------')
print("1-DArray Data\n{}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for matrix in a:
    for rowElement in matrix:
        for val in rowElement:
            print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]  Dim=3
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
------------------------------------------


In [17]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,1,2,3,4,5,6,7]).reshape(2,2,2,2)
print('---------------------------------------------------')
print("1-DArray Data\n{}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for cluster in a:
    for matrix in cluster:
        for rowElement in matrix:
            for val in rowElement:
                print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]]  Dim=4
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
	1
	2
	3
	4
	5
	6
	7
------------------------------------------


In [12]:
#2. By using numpy.nditer()

In [13]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print('---------------------------------------------------')
print("1-DArray Data={}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data=[10 20 30 40 50 60 70 80 90]  Dim=1
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
------------------------------------------


In [20]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print('---------------------------------------------------')
print("1-DArray Data\n{}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data
[[10 20 30]
 [40 50 60]
 [70 80 90]]  Dim=2
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
------------------------------------------


In [16]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print('---------------------------------------------------')
print("1-DArray Data\n{}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]  Dim=3
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
------------------------------------------


In [21]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,1,2,3,4,5,6,7]).reshape(2,2,2,2)
print('---------------------------------------------------')
print("1-DArray Data\n{}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]]  Dim=4
---------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
	1
	2
	3
	4
	5
	6
	7
------------------------------------------


In [22]:
 #By using   numpy.ndenumerate()

In [23]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print('---------------------------------------------------')
print("1-DArray Data={}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.ndenumerate(a):
    print("\t{}".format(val))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data=[10 20 30 40 50 60 70 80 90]  Dim=1
---------------------------------------------------
	((0,), np.int64(10))
	((1,), np.int64(20))
	((2,), np.int64(30))
	((3,), np.int64(40))
	((4,), np.int64(50))
	((5,), np.int64(60))
	((6,), np.int64(70))
	((7,), np.int64(80))
	((8,), np.int64(90))
------------------------------------------


In [25]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print('---------------------------------------------------')
print("1-DArray Data={}  Dim={}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.ndenumerate(a):
    print("\tIndex-{}--->Value-{}".format(val[0][0],val[1]))
print('------------------------------------------')

---------------------------------------------------
1-DArray Data=[10 20 30 40 50 60 70 80 90]  Dim=1
---------------------------------------------------
	Index-0--->Value-10
	Index-1--->Value-20
	Index-2--->Value-30
	Index-3--->Value-40
	Index-4--->Value-50
	Index-5--->Value-60
	Index-6--->Value-70
	Index-7--->Value-80
	Index-8--->Value-90
------------------------------------------


In [38]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print('---------------------------------------------------')
print("2-DArray Data\n{}  Dim{}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.ndenumerate(a):
    print("\tIndex--Row-{}, Col-{}--->Value-{}".format(val[0][0],val[0][1],val[1]))
print('------------------------------------------')

---------------------------------------------------
2-DArray Data
[[10 20 30]
 [40 50 60]
 [70 80 90]]  Dim2
---------------------------------------------------
	Index--Row-0, Col-0--->Value-10
	Index--Row-0, Col-1--->Value-20
	Index--Row-0, Col-2--->Value-30
	Index--Row-1, Col-0--->Value-40
	Index--Row-1, Col-1--->Value-50
	Index--Row-1, Col-2--->Value-60
	Index--Row-2, Col-0--->Value-70
	Index--Row-2, Col-1--->Value-80
	Index--Row-2, Col-2--->Value-90
------------------------------------------


In [43]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print('---------------------------------------------------')
print("2-DArray Data\n{}  Dim{}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.ndenumerate(a):
    print("\tIndex--Matrix-{}, Row-{}, Col-{}--->Value-{}".format(val[0][0],val[0][1],val[0][2],val[1]))
print('------------------------------------------')

---------------------------------------------------
2-DArray Data
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]  Dim3
---------------------------------------------------
	Index--Matrix-0, Row-0, Col-0--->Value-10
	Index--Matrix-0, Row-0, Col-1--->Value-20
	Index--Matrix-0, Row-1, Col-0--->Value-30
	Index--Matrix-0, Row-1, Col-1--->Value-40
	Index--Matrix-1, Row-0, Col-0--->Value-50
	Index--Matrix-1, Row-0, Col-1--->Value-60
	Index--Matrix-1, Row-1, Col-0--->Value-70
	Index--Matrix-1, Row-1, Col-1--->Value-80
------------------------------------------


In [44]:
import numpy as np
a=np.arange(2*3*3).reshape(2,3,3)
print('---------------------------------------------------')
print("2-DArray Data\n{}  Dim{}".format(a,a.ndim))
print('---------------------------------------------------')
for val in np.ndenumerate(a):
    print("\tIndex--Matrix-{}, Row-{}, Col-{}--->Value-{}".format(val[0][0],val[0][1],val[0][2],val[1]))
print('------------------------------------------')

---------------------------------------------------
2-DArray Data
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]  Dim3
---------------------------------------------------
	Index--Matrix-0, Row-0, Col-0--->Value-0
	Index--Matrix-0, Row-0, Col-1--->Value-1
	Index--Matrix-0, Row-0, Col-2--->Value-2
	Index--Matrix-0, Row-1, Col-0--->Value-3
	Index--Matrix-0, Row-1, Col-1--->Value-4
	Index--Matrix-0, Row-1, Col-2--->Value-5
	Index--Matrix-0, Row-2, Col-0--->Value-6
	Index--Matrix-0, Row-2, Col-1--->Value-7
	Index--Matrix-0, Row-2, Col-2--->Value-8
	Index--Matrix-1, Row-0, Col-0--->Value-9
	Index--Matrix-1, Row-0, Col-1--->Value-10
	Index--Matrix-1, Row-0, Col-2--->Value-11
	Index--Matrix-1, Row-1, Col-0--->Value-12
	Index--Matrix-1, Row-1, Col-1--->Value-13
	Index--Matrix-1, Row-1, Col-2--->Value-14
	Index--Matrix-1, Row-2, Col-0--->Value-15
	Index--Matrix-1, Row-2, Col-1--->Value-16
	Index--Matrix-1, Row-2, Col-2--->Value-17
------------------------------