In [1]:
#Numpy--Indexing Operation

In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Content of a")
print(a)
print("Dim of a =",a.ndim)

Content of a
[10 20 30 40 50 60 70 80 90]
Dim of a = 1


In [4]:
#Indexing Operation  on 1D
print(a)

[10 20 30 40 50 60 70 80 90]


In [5]:
#Get 30 Element from 1dArray
print(a[3])

40


In [6]:
print(a[len(a)-1])

90


In [7]:
print(a[a.size-1])

90


In [8]:
#Indexing Operation  on 2D

In [9]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(9,1)
print("Content of a")
print(a)
print("Dim of a =",a.ndim)
print("Shape of a =",a.shape)

Content of a
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
Dim of a = 2
Shape of a = (9, 1)


In [10]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(1,9)
print("Content of a")
print(a)
print("Dim of a =",a.ndim)
print("Shape of a =",a.shape)

Content of a
[[10 20 30 40 50 60 70 80 90]]
Dim of a = 2
Shape of a = (1, 9)


In [11]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(9,)
print("Content of a")
print(a)
print("Dim of a =",a.ndim)
print("Shape of a =",a.shape)

Content of a
[10 20 30 40 50 60 70 80 90]
Dim of a = 1
Shape of a = (9,)


In [12]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Content of a")
print(a)
print("Dim of a =",a.ndim)
print("Shape of a =",a.shape)

Content of a
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dim of a = 2
Shape of a = (3, 3)


In [13]:
#Get an Element 50 from 2DArray
print(a[1,1])

50


In [14]:
#Get an Element 60 from 2DArray
print(a[1,2])

60


In [17]:
#Get an Element 50 from 2DArray
print(a[-2,-2])

50


In [18]:
#Indexing Operation  on 3D

In [22]:
import numpy as np
a=np.arange(27).reshape(3,3,3)
print("Content of a")
print(a)
print("Dim of a =",a.ndim)
print("Shape of a =",a.shape)

Content of a
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dim of a = 3
Shape of a = (3, 3, 3)


In [25]:
#Get First Matrix From 3D
print(a[0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
#Get Second Matrix From 3D
print(a[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [27]:
#Get Third Matrix From 3D
print(a[2])

[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [28]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [29]:
#Get 13 from 3D Array
print(a[1,1,1])

13
