In [1]:
#Numpy--Slicing Operations on 1-D

In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Content of a")
print(a)
print("Dim of a =",a.ndim)
print("Shape of a =",a.shape)

Content of a
[10 20 30 40 50 60 70 80 90]
Dim of a = 1
Shape of a = (9,)


In [3]:
#Get 10 20 30 40  from 1D Array
print(a[0:4])

[10 20 30 40]


In [4]:
#Get 10 20 30 40  from 1D Array
print(a[:4])

[10 20 30 40]


In [5]:
#Get 10 20 30 40  from 1D Array
print(a[:4:])

[10 20 30 40]


In [6]:
print(a[::2])

[10 30 50 70 90]


In [7]:
print(a[4:1:-1])

[50 40 30]


In [8]:
print(a[::-2])

[90 70 50 30 10]


In [9]:
#Numpy--Slicing Operations on 2-D

In [10]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45,55,77,88,99]).reshape(4,4)
print("Content of ndarray")
print(a)
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)

Content of ndarray
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]
Dim of a= 2
Shape of a= (4, 4)


In [11]:
#Get [60,70,80] from 2D Array
print(a[1:2,1:4])

[[60 70 80]]


In [12]:
#Get [60,70,80] from 2D Array
print(a[1:2,1:])

[[60 70 80]]


In [13]:
#Get [60,70,80] from 2D Array with -ve Indices
print(a[-3:-2,-3:])

[[60 70 80]]


In [15]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]


In [16]:
#Get 60,70,25,35 from 2D Array
print(a[1:3,1:3])

[[60 70]
 [25 35]]


In [18]:
#Get 60,70,25,35 from 2D Array with -VE Indices
print(a[-3:-1,-3:-1,])

[[60 70]
 [25 35]]


In [19]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]


In [20]:
# Get 10,50,90,55,30,70,35,88
print(a[::,::2])

[[10 30]
 [50 70]
 [90 35]
 [55 88]]


In [21]:
#Get 40,80,45,99
print(a[::,3:])

[[40]
 [80]
 [45]
 [99]]


In [26]:
#Get 40,80,45,99
print(a[::,-1:])

[[40]
 [80]
 [45]
 [99]]


In [27]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]


In [28]:
# Get 10,55,40,99
print(a[::3,::3])

[[10 40]
 [55 99]]
