In [1]:
#Create 3D Array with Random Integer Values with shape(3,3,3)

In [2]:
import numpy.random as r
a=r.randint(10,20,size=(3,3,3))
print("3D Array")
print(a)

3D Array
[[[14 19 17]
  [12 18 17]
  [16 12 17]]

 [[11 12 18]
  [15 17 14]
  [13 15 13]]

 [[17 11 15]
  [18 13 17]
  [18 13 14]]]


In [3]:
#Get First Two Matrices from 3D
print(a[0:2])

[[[14 19 17]
  [12 18 17]
  [16 12 17]]

 [[11 12 18]
  [15 17 14]
  [13 15 13]]]


In [4]:
#get First and Last Matrix
print(a[::2])

[[[14 19 17]
  [12 18 17]
  [16 12 17]]

 [[17 11 15]
  [18 13 17]
  [18 13 14]]]


In [5]:
print(a)

[[[14 19 17]
  [12 18 17]
  [16 12 17]]

 [[11 12 18]
  [15 17 14]
  [13 15 13]]

 [[17 11 15]
  [18 13 17]
  [18 13 14]]]


In [7]:
#Get All 0th row of all Columns of all Matrices
print(a[::,0:1,::])

[[[14 19 17]]

 [[11 12 18]]

 [[17 11 15]]]


In [8]:
#Get All 0th Col of all Rows of all Matrices
print(a[::,::,:1])

[[[14]
  [12]
  [16]]

 [[11]
  [15]
  [13]]

 [[17]
  [18]
  [18]]]


In [9]:
print(a)

[[[14 19 17]
  [12 18 17]
  [16 12 17]]

 [[11 12 18]
  [15 17 14]
  [13 15 13]]

 [[17 11 15]
  [18 13 17]
  [18 13 14]]]


In [11]:
#Get First and Last Matrices 2nd Row Elements of Correcposnding Matrices
print(a[::2,1:2,::])

[[[12 18 17]]

 [[18 13 17]]]


In [12]:
# Get last matrix last row last last two elements [13,14]
print(a[2:,2:,1:3])

[[[13 14]]]
