In [1]:
#Create an 1d Array Object with Elements

In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("1D Array Data")
print(a)
print("----------------------------------------------")
#Get the Elements 10 30 70 and 90--Method-1
#Step: Get the Indices of Elements 10 30 70 and 90
ind=[0,2,-1,-3]  #List Object
#Step-2: Pass the Indices Values to 1DArray
print(a[ind])

1D Array Data
[10 20 30 40 50 60 70 80 90]
----------------------------------------------
[10 30 90 70]


In [4]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [5]:
#Get the Elements 10 90 40 10,30
ind=[0,-1,3,0,2]
print(a[ind])

[10 90 40 10 30]


In [6]:
#Method-2

In [8]:
print(a[[0,-1,3,0,2]])

[10 90 40 10 30]


In [9]:
#Create an 2d Array Object with Elements withb (Method-1)

In [11]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,55,65,75]).reshape(4,4)
print("2D Array Data")
print(a)
print("------------------------------------------")
#Get  10 30 25 and 45 from 2D Array-Method-1
#Step-1: Get the Row Indices of 10,30,25, and 45 from 2d Array
rowind=[0,0,2,3]
#Step-2: Get the Col Indices of 10,30,25, and 45 from 2d Array
colind=[0,2,2,0]
#Step-3 Pass RowIndices and Colindices to 2D Array
print(a[rowind,colind])

2D Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]
 [45 55 65 75]]
------------------------------------------
[10 30 25 45]


In [12]:
#(Method-2)

In [13]:
#Get  10 30 25 and 45 from 2D Array-Method-2
print(a[[0,0,2,3],[0,2,2,0]])

[10 30 25 45]


In [14]:
#Create an 3d Array Object with Elements

In [15]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,55,65,75]).reshape(2,4,2)
print("3D Array Data")
print(a)

3D Array Data
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 55]
  [65 75]]]


In [16]:
#Method-1
#Get the Elements 10,80,25,90
#Step-1:  Get Matrix Indices of Elements 10,80,25,90
matind=[0,0,1,1]
#Step-2:  Get Row Indices of Elements 10,80,25,90
rowind=[0,3,1,0]
#Step-3:  Get Column Indices of Elements 10,80,25,90
colind=[0,1,0,0]
#Step-3: Pass Matrix , Row and Column Indices to 3D Array
print(a[matind,rowind,colind])

[10 80 25 90]


In [17]:
#Method-2
#Get the Elements 10,80,25,90
print(a[[0,0,1,1],[0,3,1,0],[0,1,0,0]])

[10 80 25 90]
