In [1]:
#Numpy---Filtering the Data from ndarray

In [2]:
#Create 1D Array with Random 12 Integer Values

In [3]:
import numpy.random as r
a=r.randint(25,55,12)
print("Random Elements")
print(a)

Random Elements
[43 54 44 26 33 50 29 25 28 43 31 35]


In [10]:
#Get the Factors of 5 --Normal Python Code
a=[43 ,54, 44, 26, 33, 50, 29, 25, 28, 43, 31, 35]
print(a)
print("----------------------------------------------")
lst=[]
for i in a:
    if(i%5==0):
        lst.append(i)
print("Factors of 5")
print("----------------------------------------------")
print(lst)

[43, 54, 44, 26, 33, 50, 29, 25, 28, 43, 31, 35]
----------------------------------------------
Factors of 5
----------------------------------------------
[50, 25, 35]


In [13]:
import numpy.random as r
a=r.randint(25,55,12)
print("Random Elements")
print(a)
#Get all Factors of 5
#Step-1: Prepare the Condition with ndarray object
ba = (a%5==0)
print("------------------------------------------------")
print("Boolean Array={}  Type={}".format(ba,type(ba)))
print("------------------------------------------------")
print("Factors of 5:")
print(a[ba])

Random Elements
[45 25 25 26 28 49 25 36 44 44 47 46]
------------------------------------------------
Boolean Array=[ True  True  True False False False  True False False False False False]  Type=<class 'numpy.ndarray'>
------------------------------------------------
Factors of 5:
[45 25 25 25]


In [18]:
import numpy.random as r
a=r.randint(25,55,12)
print("Random Elements")
print(a)
#Get all Factors of 5
#Step-1: Prepare the Condition with ndarray object
ba = (a%5==0) & (a%3==0)
print("------------------------------------------------")
print("Boolean Array={}  Type={}".format(ba,type(ba)))
print("------------------------------------------------")
print("Factors of 5 and 3:")
print(a[ba])

Random Elements
[52 37 45 34 26 33 49 46 41 32 41 39]
------------------------------------------------
Boolean Array=[False False  True False False False False False False False False False]  Type=<class 'numpy.ndarray'>
------------------------------------------------
Factors of 5 and 3:
[45]


In [19]:
import numpy.random as r
a=r.randint(25,55,12)
print("Random Elements")
print(a)
#Get all Factors of 5
print("------------------------------------------------")
print("Factors of 5 and 3:")
print(a[(a%5==0) & (a%3==0)])

Random Elements
[41 36 47 28 42 40 26 42 48 53 35 47]
------------------------------------------------
Factors of 5 and 3:
[]


In [16]:
import numpy.random as r
a=r.randint(25,91,18)
print("Random Elements")
print(a)
#Get all Factors of 5
print("------------------------------------------------")
print("Factors of 5 and 3:")
print(a[(a%5==0) & (a%3==0)])

Random Elements
[79 40 90 60 37 90 33 36 28 85 30 39 67 62 61 83 67 25]
------------------------------------------------
Factors of 5:
[90 60 90 30]
