In [7]:
#Create an object of ndarray
import numpy as np
a=np.random.randint(100,150,size=10)
print("NDArray Object Data")
print(a)
#Search for those Elements which are Divisible by 5
b=np.where(a%5==0)
print(f"Content of b={b[0]}  Type={type(b[0])}")

NDArray Object Data
[125 129 107 142 113 138 139 147 141 135]
Content of b=[0 9]  Type=<class 'numpy.ndarray'>


In [9]:
print(a[b[0]])

[125 135]


In [12]:
#Search for those Elements which are Divisible by 5
b=np.extract(a%5==0,a)
print(f"Content of b={b}  Type={type(b)}")

Content of b=[125 135]  Type=<class 'numpy.ndarray'>


In [19]:
#Another Example
arr=np.array([10,15,20,25,30])
idx=np.where(arr>20)
print("Indices =",idx[0])
print("Value =",arr[idx])

Indices = [3 4]
Value = [25 30]


In [21]:
#Another Example
arr=np.array([2,3,4,5,6,7,8])
idx=np.where(arr%2==0)
print("Indices =",idx[0])
print("Even Elements =",arr[idx])

Indices = [0 2 4 6]
Even Elements = [2 4 6 8]


In [27]:
#Another Example
arr=np.array([2,3,4,5,6,7,8])
idx=np.where(arr%2==0,"Even","Odd")
print(idx)

['Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


In [29]:
nda=np.array([1000,2000,3000,450,550,500,750,5000])
nss=np.where(nda<=1000,nda+nda*50/100,nda)
print(nss)

[1500. 2000. 3000.  675.  825.  750. 1125. 5000.]


In [31]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
c=np.array([100,200,300,400])
d=np.array([1000,2000,3000,4000])
nss=np.where(a>2,d,c)
print(nss)

[ 100  200 3000 4000]


In [43]:
a=np.array([1,2,3,4])
print(a)
nss=np.where( (a < 2) | (a > 3) , 0 , a)
print(nss)

[1 2 3 4]
[0 2 3 0]


In [50]:
a=np.array([1,2,3,4])
print(a)
nss=np.where( (a >= 2) & (a <= 3))
print(a[nss])

[1 2 3 4]
[2 3]


In [51]:
mat = np.random.randint([ [ 5, -2,  3], [-1,  4, -6] ] )
print(mat)
print("--------------------------------------------")
nss=np.where(mat<0,0,mat)
print(nss)

[[ 5 -2  3]
 [-1  4 -6]]
--------------------------------------------
[[5 0 3]
 [0 4 0]]
