In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.extract(a>2,a)
print("Array Elements")
print(b)

Array Elements
[3 4]


In [4]:
a = np.array([1, 2, 3, 4])
cr = (a>=2) & (a<=3)
print(np.extract(cr,a))

[2 3]


In [8]:
#-------------------------------------------------------
#Working with Missing Data
#-------------------------------------------------------
#It is common to encounter missing values encoded as NaN or None in real-world datasets.
#We can use filtering to remove or replace these missing values:
data = np.array([1, 2, None, 3, 4])
# Replace missing Value with 0
data = np.where(data==None,0,data)
# Output: array([1, 2, 0, 3, 4])
print(data)

[1 2 0 3 4]


In [9]:
data = np.array([1, 2, None, 3, 4])
# Replace missing Value with 0
data = np.where(data==None,"Ravi",data)
# Output: array([1, 2, 'Ravi', 3, 4])
print(data)

[1 2 'Ravi' 3 4]


In [10]:
data = np.array([1, 2, None, 3, 4])
# Filter missing values
data = np.extract(data!=None,data)
print(data)

[1 2 3 4]


In [11]:
#Data Cleaning
#----------------------------------------------------------------
#Filtering functions enable removing unwanted outliers or invalid values:
#----------------------------------------------------------------
ages = np.array([15, 99, 87, 21, 67])
# Remove invalid ages ie. ages greater than 90
valid_ages = np.extract(ages>=25,ages)
print("Valid Ages")
print(valid_ages)

Valid Ages
[99 87 67]


In [15]:
#Reducing Memory Usage
big_array = np.random.rand(100000)
# Lots of memory used to store full array
filtered = np.where(big_array<500,None,big_array)
# Less memory for extracted elements
extracted = np.extract(big_array<0.1,big_array)
print("Number of Values in filtered array with where()=",len(filtered))
print("Number of Values in Extracted array with extract()=",len(extracted))

Number of Values in filtered array with where()= 100000
Number of Values in Extracted array with extract()= 49974
