In [2]:
#Sort the 1D Array Data
import numpy as np
a=np.random.randint(100,234,size=8)
print("1D Random Data--original ")
print(a)
#sort the Random data
a = np.sort(a)
print("1D Sorted Data in Ascending Order")
print(a)

1D Random Data--original 
[166 151 183 119 166 120 110 146]
1D Sorted Data in Ascending Order
[110 119 120 146 151 166 166 183]


In [3]:
import numpy as np
a=np.random.randint(100,234,size=8)
print("1D Random Data--original ")
print(a)
#sort the Random data
a = np.sort(a)
print("1D Sorted Data in Ascending Order")
print(a)
print("1D Sorted Data in Decsending Order")
a=a[::-1]
print(a)

1D Random Data--original 
[132 216 133 107 197 205 230 232]
1D Sorted Data in Ascending Order
[107 132 133 197 205 216 230 232]
1D Sorted Data in Decsending Order
[232 230 216 205 197 133 132 107]


In [4]:
#Sort the 2D Array Data
import numpy as np
a=np.array([15,10,25,11,12,18,29,31,13]).reshape(3,3)
print("2D Random Data--original ")
print(a)
#sort the 2D Array data
a=np.sort(a)
print("2D Sorted Data in Ascending Order")
print(a)

2D Random Data--original 
[[15 10 25]
 [11 12 18]
 [29 31 13]]
2D Sorted Data in Ascending Order
[[10 15 25]
 [11 12 18]
 [13 29 31]]


In [5]:
#Sort the 2D Array Data
import numpy as np
a=np.array([15,10,25,11,12,18,29,31,13]).reshape(3,3)
print("2D Random Data--original ")
print(a)
#sort the 2D Array data
a=np.sort(a,axis=1)  # Here axis=1 Represents Rows (Default axis=1 -->Rows)
print("2D Sorted Data in Ascending Order")
print(a)

2D Random Data--original 
[[15 10 25]
 [11 12 18]
 [29 31 13]]
2D Sorted Data in Ascending Order
[[10 15 25]
 [11 12 18]
 [13 29 31]]


In [6]:
#Sort the 2D Array Data
import numpy as np
a=np.array([15,10,25,11,12,18,29,31,13]).reshape(3,3)
print("2D Random Data--original ")
print(a)
#sort the 2D Array data
a=np.sort(a,axis=0)  # Here axis=0 Represents Coloumns (Default axis=1 -->Rows)
print("2D Sorted Data in Ascending Order")
print(a)

2D Random Data--original 
[[15 10 25]
 [11 12 18]
 [29 31 13]]
2D Sorted Data in Ascending Order
[[11 10 13]
 [15 12 18]
 [29 31 25]]


In [9]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order="name")
print("Sorted Data Based on Name--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")   


Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Name--Ascending Order
('Rajesh', 40, 165)
('Raju', 35, 174)
('Rakesh', 34, 171)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Ranjeet', 40, 169)
('Rossum', 60, 162)
----------------------------------------------------


In [10]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order="age")
print("Sorted Data Based on Age--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")  

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Name--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)
----------------------------------------------------


In [12]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order="height")[::-1]
print("Sorted Data Based on Height-- Decsending Order")
for record in a:
    print(record)
print("----------------------------------------------------")  

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Name--Ascending Order
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Raju', 35, 174)
('Rakesh', 34, 171)
('Ranjeet', 40, 169)
('Rajesh', 40, 165)
('Rossum', 60, 162)
----------------------------------------------------


In [18]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Rakesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order=("age","height"),kind="heapsort")
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")  

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Rakesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Rakesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)
----------------------------------------------------


In [19]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Rakesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order=("age","height","name"),kind="heapsort")
print("Sorted Data Based on Age, Height and Name--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")  

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Rakesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Rakesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)
----------------------------------------------------


In [20]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Rakesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order=("age","height"),kind="quicksort")
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")  

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Rakesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Rakesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)
----------------------------------------------------


In [21]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Rakesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order=("age","height"),kind="mergesort")
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")  

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Rakesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Rakesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)
----------------------------------------------------


In [22]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Rakesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")   
a=np.sort(a,order=("age","height"))
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")  

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Rakesh', 35, 175)
----------------------------------------------------
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Rakesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)
----------------------------------------------------


In [25]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
print("----------------------------------------------------")    
a=np.sort(a,order=("age","height"),kind="bubblesort")
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)
print("----------------------------------------------------")    

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
----------------------------------------------------


ValueError: sort kind must be one of 'quick', 'heap', or 'stable' (got 'bubblesort')