In [1]:
#Create Two Matrices with 2 D of Shape (2,2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]


In [2]:
#Perform Addition of Matrices ---add()
#Syntax:   varname=numpy.add(ndarray1,mdarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.add(a,b)
print("Addition of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Addition of a and b
[[11 22]
 [33 44]]


In [3]:
#Alternatively, We Perform Addition of Matrices ---Arithmetic Operator +
#Syntax:   varname=numpy.add(ndarray1,mdarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=a+b
print("Addition of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Addition of a and b
[[11 22]
 [33 44]]


In [4]:
#Perform Substraction of Matrices ---subtract()
#Syntax:   varname=numpy.subtract(ndarray1,mdarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.subtract(a,b)
print("Subtraction of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Subtraction of a and b
[[ 9 18]
 [27 36]]


In [5]:
#Perform Substraction of Matrices ---Arithmetic Operator -
#Syntax:   varname=ndarray1-mdarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=a-b
print("Subtraction of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Subtraction of a and b
[[ 9 18]
 [27 36]]


In [6]:
#Perform Multiplication of Matrices ---multiply()
#Syntax:   varname=numpy.multiply(ndarray1,mdarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.multiply(a,b)
print("Multiplication of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Multiplication of a and b
[[ 10  40]
 [ 90 160]]


In [7]:
#Perform Multiplication of Matrices ---Arithmetic Operator *
#Syntax:   varname=ndarray1*mdarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=a*b
print("Multiplication of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Multiplication of a and b
[[ 10  40]
 [ 90 160]]


In [9]:
#Perform dot Product of Matrices ---dot() or matmul()
#Rule:  Number of Columns in ndarray1 Must be equal to Number of rows in ndarray2
#    Otherwise dot() or matmul() is Not Possible
#Syntax:   varname=numpy.dot(ndarray1,ndarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print(a,a.shape)
print("----------------------------------")
print("Matrix-b")
print(b)
print(b,b.shape)
print("----------------------------------")
c=np.dot(a,b)
print("Multiplication of a and b")
print(c)
print(c,c.shape)

Matrix-a
[[10 20]
 [30 40]]
[[10 20]
 [30 40]] (2, 2)
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
[[1 2]
 [3 4]] (2, 2)
----------------------------------
Multiplication of a and b
[[ 70 100]
 [150 220]]
[[ 70 100]
 [150 220]] (2, 2)


In [10]:
#Perform Division of Matrices ---divide()
#Syntax:   varname=numpy.divide(ndarray1,ndarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.divide(a,b)
print("Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Division of a and b
[[10. 10.]
 [10. 10.]]


In [11]:
#Perform Division of Matrices ---divide()
#Syntax:   varname=numpy.divide(ndarray1,ndarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.divide(b,a)
print("Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Division of a and b
[[0.1 0.1]
 [0.1 0.1]]


In [12]:
#Perform Division of Matrices ---Arithmetic Operator /
#Syntax:   varname=ndarray1/ndarray2
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=a/b
print("Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Division of a and b
[[10. 10.]
 [10. 10.]]


In [14]:
#Perform Division of Matrices ---floor_divide()
#Syntax:   varname=numpy.floor_divide(ndarray1,ndarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.floor_divide(a,b)
print("Floor Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Floor Division of a and b
[[10 10]
 [10 10]]


In [15]:
#Perform Division of Matrices ---Arithmetic Operator //
#Syntax:   varname=ndarray1//ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=a//b
print("Floor Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Floor Division of a and b
[[10 10]
 [10 10]]


In [16]:
#Perform Modulo Division of Matrices ---mod()
#Syntax:   varname=numpy.mod(ndarray1,ndarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.mod(a,b)
print("Modulo Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Modulo Division of a and b
[[0 0]
 [0 0]]


In [18]:
#Perform Modulo Division of Matrices ---mod()
#Syntax:   varname=numpy.mod(ndarray1,ndarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.mod(b,a)
print("Modulo Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Modulo Division of a and b
[[1 2]
 [3 4]]


In [19]:
#Perform Modulo Division of Matrices ---Arithmetic Operator %
#Syntax:   varname=ndarray1%ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=a%b
print("Modulo Division of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Modulo Division of a and b
[[0 0]
 [0 0]]


In [20]:
#Perform Exponentiation of Matrices ---power()
#Syntax:   varname=numpy.power(ndarray1,ndarray2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=np.power(a,b)
print("Exponentiation of Matrices ---power() of a and b")
print(c)

Matrix-a
[[10 20]
 [30 40]]
----------------------------------
Matrix-b
[[1 2]
 [3 4]]
----------------------------------
Exponentiation of Matrices ---power() of a and b
[[     10     400]
 [  27000 2560000]]


In [ ]:
#Perform Exponentiation of Matrices ---Arithmetic Exponentiation operator **
#Syntax:   varname=ndarray1**ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-a")
print(a)
print("----------------------------------")
print("Matrix-b")
print(b)
print("----------------------------------")
c=
print("Exponentiation of Matrices ---power() of a and b")
print(c)