In [1]:
#Create an object of ndarrya Array
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8])
print("1d Array Elements")
print(a)

1d Array Elements
[10  2 13  4 14  5 15 18  8]


In [2]:
#Find Highest Element in 1DArray---amax()
#Syntax:     varname=numpy.amax(ndarray,axis)

In [4]:
b=np.amax(a)
print("Max Element=",b)

Max Element= 18


In [5]:
#Find Max Element from 2D Array
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
print("-----------------------------------")
maxv=np.amax(a)
print("Max Element=",maxv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
-----------------------------------
Max Element= 18


In [6]:
#Find Max Element from 2D Array in Coloumn-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
print("-----------------------------------")
maxv=np.amax(a)
print("Max Element=",maxv)
colmaxv=np.amax(a,axis=0)
print("Max Col-Wise=",colmaxv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
-----------------------------------
Max Element= 18
Max Col-Wise= [15 18 13]


In [7]:
#Find Max Element from 2D Array in Row-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
print("-----------------------------------")
maxv=np.amax(a)
print("Max Element=",maxv)
rowmaxv=np.amax(a,axis=1)
print("Max Row-Wise=",rowmaxv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
-----------------------------------
Max Element= 18
Max Row-Wise= [13 14 18]


In [8]:
#Find Smallest Element in 1DArray---amin()
#Syntax:     varname=numpy.amin(ndarray,axis)

In [10]:
#Create an object of ndarrya Array
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8])
print("1d Array Elements")
print(a)
b=np.amin(a)
print("Min Element=",b)

1d Array Elements
[10  2 13  4 14  5 15 18  8]
Min Element= 2


In [11]:
#Find Min Element from 2D Array
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
print("-----------------------------------")
minv=np.amin(a)
print("Max Element=",minv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
-----------------------------------
Max Element= 2


In [12]:
#Find Min Element from 2D Array in Column-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
print("------------------------------------")
minv=np.amin(a)
colminv=np.amin(a,axis=0) # Here axis=0 Represents Cols
print("Min Element=",minv)
print("Column Min Values=",colminv)
print("------------------------------------")

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
------------------------------------
Min Element= 2
Column Min Values= [4 2 5]
------------------------------------


In [13]:
#Find Min Element from 1D Array in Row-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
print("------------------------------------")
minv=np.amin(a)
rowminv=np.amin(a,axis=1) # Here axis=1 Represents Rows
print("Min Element=",minv)
print("Column Min Values=",rowminv)
print("------------------------------------")

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
------------------------------------
Min Element= 2
Column Min Values= [2 4 8]
------------------------------------


In [14]:
#Find Min Element from 3D Array in Row-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8,12,9,10,25,8,4,14]).reshape(2,4,2)
print("3d Array Elements")
print(a)
print("------------------------------------")
maxv=np.amax(a)
print("Max Element=",maxv)
Fcolmaxv=np.amax(a[0],axis=0)
Scolmaxv=np.amax(a[1],axis=0)
print("First Matrix Col Max Vals\n",Fcolmaxv)
print("Second Matrix Col Max Vals\n",Scolmaxv)

3d Array Elements
[[[10  2]
  [13  4]
  [14  5]
  [15 18]]

 [[ 8 12]
  [ 9 10]
  [25  8]
  [ 4 14]]]
------------------------------------
Max Element= 25
First Matrix Col Max Vals
 [15 18]
Second Matrix Col Max Vals
 [25 14]


In [15]:
#Finding the Mean of ndarray Elements--mean()
#Syntax:   varname=numpy.mean(ndarray,axis)

In [16]:
#Consider the following ndarray and find mean
import numpy as np
a=np.array([2,3,1,4])
print("1D Array Data")
print(a)
mv=np.mean(a)
print("Mean of ndarray=",mv)

1D Array Data
[2 3 1 4]
Mean of ndarray= 2.5


In [19]:
#Consider the following 2darray and find mean
import numpy as np
a=np.array([2,3,1,4]).reshape(2,2)
print("2D Array Data")
print(a)
print("-------------------------")
mv=np.mean(a)
print("Mean of ndarray=",mv)
print("-------------------------")
colmv=np.mean(a,axis=0)
print("Col Mean of ndarray=",colmv)
print("-------------------------")
rowmv=np.mean(a,axis=1)
print("Row Mean of ndarray=",rowmv)


2D Array Data
[[2 3]
 [1 4]]
-------------------------
Mean of ndarray= 2.5
-------------------------
Col Mean of ndarray= [1.5 3.5]
-------------------------
Row Mean of ndarray= [2.5 2.5]


In [22]:
import numpy as np
a=np.random.randint(10,100,size=(2,3,3))
print("2D Array Data")
print(a)
print("-------------------------")
mv=np.mean(a)
print("Mean of ndarray\n",mv)
print("-------------------------")
colmv=np.mean(a,axis=0)
print("Col Mean of ndarray\n",colmv)
print("-------------------------")
rowmv=np.mean(a,axis=1)
print("Row Mean of ndarray\n",rowmv)

2D Array Data
[[[27 50 20]
  [19 69 55]
  [26 78 79]]

 [[20 24 75]
  [24 81 18]
  [16 88 87]]]
-------------------------
Mean of ndarray
 47.55555555555556
-------------------------
Col Mean of ndarray
 [[23.5 37.  47.5]
 [21.5 75.  36.5]
 [21.  83.  83. ]]
-------------------------
Row Mean of ndarray
 [[24.         65.66666667 51.33333333]
 [20.         64.33333333 60.        ]]


In [23]:
#Find the Mean of Opp Principle Diagnoal Elements--
import numpy as np
a=np.random.randint(2,10,size=(3,3))
print("2D Array Data")
print(a)
pd=np.diag(a)
print("Principle Diagnal Elements=",pd)
pdmv=np.mean(pd)
print("Mean of Principle Diagnal Elements=",pdmv)

2D Array Data
[[4 5 2]
 [4 8 6]
 [8 5 5]]
Principle Diagnal Elements= [4 8 5]
Mean of Principle Diagnal Elements= 5.666666666666667


In [25]:
#Find the Mean of Opp. Principle Diagnoal Elements
#Find the Mean of Opp. Principle Diagnoal Elements
a=np.random.randint(2,10,size=(3,3))
print("2D Array Data")
print(a)
b=a[[0,1,2],[2,1,0]]
print("OPP Principle Diagnoal Elements=",b)
mv=np.mean(b)
print("Mean of OPP Principle Diagnoal Elements=",mv)

2D Array Data
[[2 4 4]
 [4 4 3]
 [6 5 5]]
OPP Principle Diagnoal Elements= [4 4 6]
Mean of OPP Principle Diagnoal Elements= 4.666666666666667


In [26]:
#Find  the Median of ndarray---median()
#Syntax:   vraname=numpy.median(ndarray,axis)

In [27]:
a=np.random.randint(12,50,size=7)
print("1D Array Data")
print(a)
#Median  of 1D Array of odd Number of Elements
mdv=np.median(a)
print("Median of 1D Array=",mdv)

1D Array Data
[49 31 12 30 15 40 40]
Median of 1D Array= 31.0


In [28]:
a=np.random.randint(12,50,size=8)
print("1D Array Data")
print(a)
#Median  of 1D Array of Even Number of Elements
mdv=np.median(a)
print("Median of 1D Array=",mdv)

1D Array Data
[17 37 39 47 49 41 35 43]
Median of 1D Array= 40.0


In [29]:
#Find the median of 2d Array
a=np.random.randint(12,50,size=(3,3))
print("2D Array Data")
print(a)
print("------------------------------------")
#Median of 2D
mdv=np.median(a)
colmdv=np.median(a,axis=0)
rowmdv=np.median(a,axis=1)
print("Median=",mdv)
print("Col Median=",colmdv)
print("Row Median=",rowmdv)


2D Array Data
[[28 33 18]
 [18 16 28]
 [17 19 35]]
------------------------------------
Median= 19.0
Col Median= [18. 19. 28.]
Row Median= [28. 18. 19.]


In [30]:
#Find the Variance of ndarray--most Imp
#Syntax1:-      varname=numpy.var(ndarrayobject)
#Syntax2:-      varname=numpy.var(ndarrayobject,axis=0)
#Syntax3:-      varname=numpy.var(ndarrayobject,axis=1)

In [31]:
#Find the Variance of ndarray--most Imp
import numpy as np
a=np.array([2,3,1,4])
print("1D Array Data")
print(a)
v=np.var(a)
print("Variance=",v)

1D Array Data
[2 3 1 4]
Variance= 1.25


In [32]:
#Find the Variance of ndarray--most Imp
import numpy as np
a=np.array([2,3,1,4]).reshape(2,2)
print("---------------------------------")
print("2D Array Data")
print(a)
print("---------------------------------")
v=np.var(a)
cv=np.var(a,axis=0)
rv=np.var(a,axis=1)
print("---------------------------------")
print("Variance=",v)
print("Col Variance=",cv)
print("Row Variance=",rv)


---------------------------------
2D Array Data
[[2 3]
 [1 4]]
---------------------------------
---------------------------------
Variance= 1.25
Col Variance= [0.25 0.25]
Row Variance= [0.25 2.25]


In [ ]:
#Find the standard Deviation= sqrt(var) of ndarray--most Imp
#Syntax1:-      varname=numpy.std(ndarrayobject)

#Syntax2:-      varname=numpy.std(ndarrayobject,axis=0)
#Syntax3:-      varname=numpy.std(ndarrayobject,axis=1)