In [2]:
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Matrix-A")
print(a)
print("Dim of a=",a.ndim)
print("shape of a=",a.shape)
print('---------------------------------------')
#flatten the ndarray Object
b=a.flatten()
print("Content of b")
print(b)
print("Dim of b=",b.ndim)
print("shape of b=",b.shape)
print('---------------------------------------')

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dim of a= 2
shape of a= (3, 3)
---------------------------------------
Content of b
[10 20 30 40 50 60 70 80 90]
Dim of b= 1
shape of b= (9,)
---------------------------------------


In [3]:
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,75,45,55]).reshape(2,4,2)
print("Matrix-A")
print(a)
print("Dim of a=",a.ndim)
print("shape of a=",a.shape)
print('---------------------------------------')
#flatten the ndarray Object
b=a.flatten()
print("Content of b")
print(b)
print("Dim of b=",b.ndim)
print("shape of b=",b.shape)
print('---------------------------------------')

Matrix-A
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]
Dim of a= 3
shape of a= (2, 4, 2)
---------------------------------------
Content of b
[10 20 30 40 50 60 70 80 90 15 25 35 45 75 45 55]
Dim of b= 1
shape of b= (16,)
---------------------------------------


In [4]:
print("ID of a=",id(a))
print("ID of b=",id(b))

ID of a= 1761394160432
ID of b= 1761394161680


In [5]:
#Check the Base
print("Flatten Array Base =",b.base)

Flatten Array Base = None


In [6]:
print(a)

[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]


In [7]:
print(a[0,1,1])

40


In [8]:
print(a)

[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]


In [9]:
print(b)

[10 20 30 40 50 60 70 80 90 15 25 35 45 75 45 55]


In [10]:
a[-1]=550

In [11]:
print(a)

[[[ 10  20]
  [ 30  40]
  [ 50  60]
  [ 70  80]]

 [[550 550]
  [550 550]
  [550 550]
  [550 550]]]


In [16]:
a[-1]=55

In [17]:
print(a)

[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[55 55]
  [55 55]
  [55 55]
  [55 55]]]


In [18]:
print(b)

[10 20 30 40 50 60 70 80 90 15 25 35 45 75 45 55]


In [19]:
#Flatten the ndarray data by using ravel()
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Matrix-A")
print(a)
print("Dim of a=",a.ndim)
print("shape of a=",a.shape)
print('---------------------------------------')
#flatten the ndarray Object--ravel()
b=a.ravel()
print("Content of b")
print(b)
print("Dim of b=",b.ndim)
print("shape of b=",b.shape)
print('---------------------------------------')

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dim of a= 2
shape of a= (3, 3)
---------------------------------------
Content of b
[10 20 30 40 50 60 70 80 90]
Dim of b= 1
shape of b= (9,)
---------------------------------------


In [20]:
print("ID of Original ndarray a=",id(a))
print("ID of Ravelled ndarray b=",id(b))

ID of Original ndarray a= 1761434731312
ID of Ravelled ndarray b= 1761394163024


In [21]:
#Do the changes on Both ndarray Object
a[0][0]=11

In [22]:
print(a)
print("----------------------")
print(b)

[[11 20 30]
 [40 50 60]
 [70 80 90]]
----------------------
[11 20 30 40 50 60 70 80 90]


In [24]:
b[1]=155

In [25]:
print(a)
print("----------------------")
print(b)

[[ 11 155  30]
 [ 40  50  60]
 [ 70  80  90]]
----------------------
[ 11 155  30  40  50  60  70  80  90]


In [26]:
#Update 0th Row of ndarray a
a[0:1,:]=[100,200,300]

In [27]:
print(a)

[[100 200 300]
 [ 40  50  60]
 [ 70  80  90]]


In [28]:
print(b)

[100 200 300  40  50  60  70  80  90]


In [29]:
#Check for Base
print("Base of Ravelled Array b=",b.base)

Base of Ravelled Array b= [100 200 300  40  50  60  70  80  90]


In [30]:
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,75,45,55]).reshape(2,4,2)
print("Matrix-A")
print(a)
print("Dim of a=",a.ndim)
print("shape of a=",a.shape)
print('---------------------------------------')
#flatten the ndarray Object
b=a.ravel()
print("Content of b")
print(b)
print("Dim of b=",b.ndim)
print("shape of b=",b.shape)
print('---------------------------------------')

Matrix-A
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]
Dim of a= 3
shape of a= (2, 4, 2)
---------------------------------------
Content of b
[10 20 30 40 50 60 70 80 90 15 25 35 45 75 45 55]
Dim of b= 1
shape of b= (16,)
---------------------------------------


In [31]:
#Modify the Elements
#a[:,3:,1:]=[81,56]---ValueError: could not broadcast input array from shape (2,) into shape (2,1,1)

In [32]:
a[0][3][1]=81
a[1][3][1]=56

In [33]:
print(a)

[[[10 20]
  [30 40]
  [50 60]
  [70 81]]

 [[90 15]
  [25 35]
  [45 75]
  [45 56]]]


In [34]:
print(b)

[10 20 30 40 50 60 70 81 90 15 25 35 45 75 45 56]
