In [2]:
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Ndarray Data")
print(a)
print('---------------------------------------')

Ndarray Data
[10 20 30 40 50 60 70 80 90]
---------------------------------------


In [3]:
#Append the Data 25 at the end of 1Darray--by using append()
#Syntax:   numpy.append(1DArray,Value)
#Syntax:   numpy.append(1DArray,[Val1,Val2,..,Val-n])

In [4]:
#Append the Data 25 at the end of 1Darray--by using append()
np.append(a,25)

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 25])

In [5]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [6]:
#Append the Data 25 at the end of 1Darray--by using append()
a=np.append(a,25)
print(a)

[10 20 30 40 50 60 70 80 90 25]


In [7]:
#Append the Data 35,45,55 at the end of 1Darray--by using append()
a=np.append(a,[35,45,55])
print(a)

[10 20 30 40 50 60 70 80 90 25 35 45 55]


In [8]:
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Ndarray Data")
print(a,id(a))
print('---------------------------------------')

Ndarray Data
[10 20 30 40 50 60 70 80 90] 2380773043984
---------------------------------------


In [9]:
a=np.append(a,[11,22,33])
print("Ndarray Data")
print(a,id(a))

Ndarray Data
[10 20 30 40 50 60 70 80 90 11 22 33] 2380812341712


In [10]:
#Insert the Values in 1D Array
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Ndarray Data")
print(a,id(a))
print('---------------------------------------')

Ndarray Data
[10 20 30 40 50 60 70 80 90] 2380773043696
---------------------------------------


In [11]:
#Insert the Values 35 at Index 2 in 1D Array
np.insert(a,2,35)

array([10, 20, 35, 30, 40, 50, 60, 70, 80, 90])

In [12]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [13]:
a=np.insert(a,2,35)
print(a)

[10 20 35 30 40 50 60 70 80 90]


In [14]:
#Insert [100,200,300,400] at 4th Index of 1D Array
a=np.insert(a,4,[100,200,300,400])
print(a)

[ 10  20  35  30 100 200 300 400  40  50  60  70  80  90]


In [15]:
np.insert(a,[1,3],[21,41])

array([ 10,  21,  20,  35,  41,  30, 100, 200, 300, 400,  40,  50,  60,
        70,  80,  90])

In [16]:
#Insert the Values in 1D Array
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60])
print("Ndarray Data")
print(a,id(a))
print('---------------------------------------')

Ndarray Data
[10 20 30 40 50 60] 2380812344016
---------------------------------------


In [17]:
a=np.insert(a,[1,3],[21,41])
print(a)

[10 21 20 30 41 40 50 60]


In [18]:
#Insert a Row in 2DArray
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("2ddarray Data")
print(a)
print('---------------------------------------')

2ddarray Data
[[10 20 30]
 [40 50 60]
 [70 80 90]]
---------------------------------------


In [19]:
#Insert row [11,22,33] at 1 Row of 2d
a=np.insert(a,1,[11,22,33],axis=0)

In [20]:
print(a)

[[10 20 30]
 [11 22 33]
 [40 50 60]
 [70 80 90]]


In [21]:
#Insert at 1 column [55,65,75,85] of 2d
a=np.insert(a,1,[55,65,75,85],axis=1)

In [22]:
print(a)

[[10 55 20 30]
 [11 65 22 33]
 [40 75 50 60]
 [70 85 80 90]]


In [23]:
#Insert row [10,20,30,40] at Last in 2d
a=np.insert(a,len(a),[10,20,30,40],axis=0)

In [24]:
print(a)

[[10 55 20 30]
 [11 65 22 33]
 [40 75 50 60]
 [70 85 80 90]
 [10 20 30 40]]


In [25]:
#Insert Column [11,21,31,41,51] at Last in Begining
a=np.insert(a,0,[11,21,31,41,51],axis=1)

In [26]:
print(a)

[[11 10 55 20 30]
 [21 11 65 22 33]
 [31 40 75 50 60]
 [41 70 85 80 90]
 [51 10 20 30 40]]


In [27]:
#Update all the 3rd Col Values as [21,22,23,24,25]
a[0:1, 3:4]=21
a[1:2, 3:4]=22
a[2:3, 3:4]=23
a[3:4, 3:4]=24
a[4:5, 3:4]=25

In [28]:
print(a)

[[11 10 55 21 30]
 [21 11 65 22 33]
 [31 40 75 23 60]
 [41 70 85 24 90]
 [51 10 20 25 40]]
